ams_staff/urls.py
from django.urls import path
from . import views

app_name = 'ams_staff'
urlpatterns = [
    
    path('staff-base/',views.staff_base,name='staff_base'),
    
    # student
    path('staff-view-students/',views.staff_view_students,name='staff_view_students'),
    path('add-student/',views.ADD_STUDENT,name='add_student'),
    
    # subjects
    path('select-subject/',views.staff_select_subject,name='staff_select_subject'),
    path('edit-subject/',views.staff_edit_subject,name='staff_edit_subject'),

    # mark attendance
    path('mark-attendance/',views.staff_mark_attendance,name='staff_mark_attendance'),

    # enter att
    path('enter-attendance/<int:id>',views.staff_enter_attendance,name='staff_enter_attendance'),

    # view attendance
    path('view-attendance/',views.staff_view_attendance,name='staff_view_attendance'),


    # report
    #path('report/',views.staff_report,name='staff_report'),
   path('report/', views.generate_attendance_report, name='attendance_report'),

    

]


attende/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('ams_admin/', include('ams_admin.urls')),
    path('ams_staff/', include('ams_staff.urls')),
    path('ams_student/', include('ams_student.urls')),

   

    
  

] + static (settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

ams_staff/models.py
from django.db import models
from django.contrib.auth.models import User

from ams_admin.models import Semester,Session_Year,Staff,Subject

# Create your models here.


class Student(models.Model):
    admin = models.OneToOneField(User,on_delete=models.CASCADE,related_name='staff_student_profile')
    semester_id=models.ForeignKey(Semester,on_delete=models.DO_NOTHING,blank=True,null=True)
    session_year_id=models.ForeignKey(Session_Year,on_delete=models.DO_NOTHING,blank=True,null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.admin.first_name + ' ' + self.admin.last_name
    
class Attendance(models.Model):
    staff = models.ForeignKey(Staff,on_delete=models.CASCADE,null=True)
    student = models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,null=True)
    is_present = models.BooleanField(default=False)
    date = models.DateTimeField(null=True)

    def __str__(self):
        return self.student.admin.first_name + ' ' + self.student.admin.last_name + ' ' +self.subject.name 

ams_staff/forms.py
"""from django import forms
from accounts.models import Profile
class StudentRegisterForm(forms.Form):
    first_name = forms.CharField(label="First name", max_length=100)
    last_name = forms.CharField(label="Last name", max_length=100)
    email = forms.EmailField(label='Email')
    username = forms.CharField(label="Username")
    password = forms.CharField(widget=forms.PasswordInput())"""
    

ams_staff/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, auth
from accounts.models import Profile
from ams_admin.models import Session_Year,Semester
from ams_staff.models import Student,Attendance

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ams_staff.EmailBackEnd import EmailBackEnd
from ams_admin.models import Session_Year,Semester,Subject,Staff    
#from .forms import StudentRegisterForm


def staff_base(request):
    return render(request,'staff_base.html')
    


# student

def staff_view_students(request):
    students = User.objects.all().filter(profile__role = 2)
    context = {
        'students': students
    }
    return render(request,'includes/staff_view_student.html',context)
    


def ADD_STUDENT(request):
    semester=Semester.objects.all()
    session_year=Session_Year.objects.all()
    
    if request.method == "POST":
        first_name=request.POST.get('first_name')
        last_name=request.POST.get('last_name')
        email=request.POST.get('email')
        username=request.POST.get('username')
        password=request.POST.get('password')
        semester_id = request.POST.get('semester_id')
        session_year_id = request.POST.get('session_year_id')
       

        
        if User.objects.filter(email=email).exists():
            messages.warning(request,'Email Is Already Taken')
            return redirect('ams_staff:add_student')
        if User.objects.filter(username=username).exists():
            messages.warning(request,'Username Is Already Taken')
            return redirect('ams_staff:add_student')
        else:
            user = User(
                first_name = first_name,
                last_name = last_name,
                username = username,
                email = email,
                
            )
            user.set_password(password)
            user.save()
            user.profile.role = 2
            user.profile.is_verified = True
            user.save()
            
            semester =Semester.objects.get(id = semester_id) 
            session_year = Session_Year.objects.get(id=session_year_id)


            student = Student(
                admin = user,
                session_year_id = session_year,
                semester_id = semester,
            )
            student.save()
            messages.success(request,user.first_name + " " + user.last_name + " Is Successfully Added")
            return redirect('ams_staff:add_student')

            
    context = { 
        'semester':semester,
        'session_year':session_year,
    }
    return render(request,'includes/add_student.html',context)


# select subject
def staff_select_subject(request):
    return render(request,'includes/staff_select_subject.html')


# edit subject
def staff_edit_subject(request):
    return render(request,'includes/staff_edit_subject.html')



# mark attendance
def staff_mark_attendance(request):
    context={}
    try:
        user = request.user
        staff = Staff.objects.get(admin = user)
        subject = Subject.objects.all().filter( staff = staff )
        context = {
        'subject':subject,
        }

    except:
        print("-- No --")
    
    return render(request,'includes/staff_mark_attendance.html',context)

# enter attendance
def staff_enter_attendance(request,id):
    print(id)
    
                
    students = None    
    try:
        subject = Subject.objects.get(id = id)
        semester = subject.semester_id
        students = Student.objects.all().filter(semester_id  = semester)
    except:
        print("--ERROR--")

    context = {
        'students':students
    }

    if request.method == 'POST':
        try:
            date = request.POST.get('date')
            print(date)
            present_students = request.POST.getlist('attendees')
            print(present_students)

            staff = Staff.objects.get(admin = request.user)
            subject = Subject.objects.get(id = id)
            semester_id = subject.semester
            all_students = Student.objects.all().filter(semester_id = semester_id) 

            for st in all_students:    
                att = Attendance(
                    staff = staff,
                    subject = subject,
                    student = st,
                    is_present = False,
                    date = date
                )
                att.save()
                print(st)

                print(present_students)
                if str(st.admin_id) in present_students:
                    att.is_present = True
                    att.save()
            messages.error(request,"Success")
        except:
            messages.error(request,"ERROR")



        """ for s in present_students:
            student = Student.objects.get(admin_id = s)
            att = Attendance(
                staff = staff,
                subject = subject,
                student = student,
                is_present = True,
                date = date
            )
            att.save()

        s = present_students[0]
        student = Student.objects.get(admin_id = s)
        semester_id = student.semester_id 
        all_students = Student.objects.all().filter(semester_id = semester_id) 
        
        for st in all_students:    
            if st.admin_id not in present_students:
                 att = Attendance(
                    staff = staff,
                    subject = subject,
                    student = student,
                    is_present = False,
                    date = date
                )
                att.save() 
                print(st)
    
 """


    return render(request,'includes/staff_enter_attendance.html',context)




'''def calculate_attendance_percentage(student):
    total_classes = Attendance.objects.filter(student=student).count()
    if total_classes == 0:
        return 0
    present_classes = Attendance.objects.filter(student=student, is_present=True).count()
    attendance_percentage = (present_classes / total_classes) * 100
    return round(attendance_percentage, 2)  # Rounded to two decimal places


from django.shortcuts import render
from django.db.models import Avg

def generate_attendance_report(request):
    students = Student.objects.all()
    attendance_data = []

    for student in students:
        attendance_percentage = calculate_attendance_percentage(student)
        attendance_data.append({
            'student': student,
            'attendance_percentage': attendance_percentage
        })

    average_attendance = Attendance.objects.aggregate(average=Avg('is_present'))['average'] * 100

    context = {
        'attendance_data': attendance_data,
        'average_attendance': round(average_attendance, 2)
    }

    return render(request, 'includes/attendance_report.html', context)'''



from django.db.models import Count

def generate_attendance_report(request):
    students = Student.objects.all()

    attendance_report = []
    for student in students:
        total_days = Attendance.objects.filter(student=student).count()
        present_days = Attendance.objects.filter(student=student, is_present=True).count()

        if total_days > 0:
            percentage = (present_days / total_days) * 100
        else:
            percentage = 0

        attendance_report.append({
            'student': student,
            'percentage': percentage
        })

    return render(request, 'includes/attendance_report.html', {'attendance_report': attendance_report})


# view attendance
def staff_view_attendance(request):
    return render(request,'includes/staff_view_attendance.html')


# report
def staff_report(request):
    return render(request,'includes/staff_report.html')


ams_staff/templates/includes/add_student.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <form method="post" action="{% url 'ams_staff:add_student' %}">
                    {% csrf_token %}
                    <div class="col-12">
                        <h5 class="form-title"><span>Add Student</span></h5>
                    </div>
                    {% include 'includes/messages.html' %}
                    <div class="col-sm-11">
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control" name="first_name" required >
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control" name="last_name" required >
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text" class="form-control" name="email" required >
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username" required >
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password" required >
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                             <label>Semester</label>
                                <select class="form-control" name="semester_id" required>
                                        <option>Select Semester</option>
                                        {% for i in semester %}
                                        <option value="{{i.id}}">{{i.name}}</option>
                                        {% endfor %}
                                        
                                </select>
                        </div>
                    </div>
                    <div class="col-sm-11">
                        <div class="form-group">
                             <label>Session Year</label>
                                <select class="form-control"name="session_year_id" required>
                                        <option>Select Session Year</option>
                                        {% for i in session_year %}
                                        <option value="{{i.id}}">{{i.session_start}} To {{i.session_end}}</option>
                                        {% endfor %}
                                </select>
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Add Student</button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ams_staff/templates/includes/attendance_report.html

{% extends 'staff_base.html' %}
{% block content %}
<!--<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Report</title>
</head>
<body>
    <h1>Attendance Report</h1>

    <table>
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Attendance Percentage</th>
            </tr>
        </thead>
        <tbody>
            {% for data in attendance_data %}
            <tr>
                <td>{{ data.student.admin.first_name }} {{ data.student.admin.last_name }}</td>
                <td>{{ data.attendance_percentage }}%</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <p>Average Attendance Percentage: {{ average_attendance }}%</p>
</body>
</html>-->

<!DOCTYPE html>
<html>
<head>
    <title>Attendance Report</title>
    <style>
        .student-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }
        
        .student-name {
            flex: 1;
        }
        
        .attendance-percentage {
            width: 100px;
        }
        
        .below-75 {
            color: red;
        }
        
        .above-75 {
            color: green;
        }
    </style>
</head>
<body>
    <h1>Attendance Report</h1>
    <table>
        {% for entry in attendance_report %}
            <div class="student-row">
                <span class="student-name">{{ entry.student }}</span>
                <span class="attendance-percentage {% if entry.percentage < 75 %}below-75{% else %}above-75{% endif %}">
                    {{ entry.percentage }}%
                </span>
            </div>
        {% endfor %}
    </table>
</body>
</html>

{% endblock %}

ams_staff/templates/includes/messages.html
{% if messages %}
                    {% for message in messages %}
                     {% if message.tags == 'error' %}
                   <div class="alert alert-danger alert-dismissible fade show" role="alert">
                       {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                     {% endif %}  
                    {% endfor %}
                   {% endif %}

                   {% if messages %}
                   {% for message in messages %}
                    {% if message.tags == 'success' %}
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                      {{message}}
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                     </button>
                   </div>
                    {% endif %}  
                   {% endfor %}
                  {% endif %}
                  {% if messages %}
                   {% for message in messages %}
                    {% if message.tags == 'warning' %}
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                      {{message}}
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                       <span aria-hidden="true">&times;</span>
                     </button>
                   </div>
                    {% endif %}  
                   {% endfor %}
                  {% endif %}

ams_staff/templates/includes/staff_edit_subject.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Edit Subject</h1>

</div>
{% endblock %}

ams_staff/templates/includes/staff_enter_attendance.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Mark Attendence</h1>


    <div>

        <form method="POST">
            {% csrf_token %}
            <div id="student attendance" class="p-5">
                <p>Date: <input type="date" id="datepicker" name="date" style="padding:0.5em;margin:0 1em 0 1em;"></p>
                <br />
                <p>Select attendees</p>
                <select class="multiple-select" multiple multiselect-search="true" multiselect-select-all="true" name="attendees" style="display:block;width:360px;padding:1.5em;">
                    {% for s in students %}
                        <option value="{{s.admin.pk}}"> {{s.admin.first_name}}</option>
                    {% endfor %}
                </select>
                <input class="btn btn-primary" type="submit" value="Submit Attendance" >
            </div>
        </form>


        {% for m in messages %}
            <h2> {{ m }} </h2>
        {% endfor %}

           
        </div>
    </div>




</div>
{% endblock %}

ams_staff/templates/includes/staff_header.html
{% load static %}

<div class="header">
    <div class="header-left mt-1">
        <h1>AMS</h1>
    </div>        
    <a href="javascript:void(0);" id="toggle_btn">
    <i class="fas fa-align-left"></i>
    </a>
    <div class="top-nav-search mt-3">
       <h4><strong>Welcome</strong>&nbsp;<span>{{user.first_name}} {{user.last_name}}</span></h4>
    </div>
    <a class="mobile_btn" id="mobile_btn">
    <i class="fas fa-bars"></i>
    </a>
    <ul class="nav user-menu">
       
       <li class="nav-item dropdown has-arrow">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
          <span class="user-img"><img class="rounded-circle" width="31" alt="Profile"></span>
          </a>
          <div class="dropdown-menu">
             <div class="user-header">
                <div class="avatar avatar-sm">
                   
                </div>
                <div class="user-text">
                   <h6>{{user.first_name}}&nbsp; {{user.last_name}}</h6>
                   {% if request.user.profile.role == 0 %} 
                   <p class="text-muted mb-0">Admin</p>
                   {% elif request.user.profile.role == 1 %} 
                   <p class="text-muted mb-0">Staff</p>
                   {% else  %} 
                   <p class="text-muted mb-0">Student</p>
                   {% endif %}
                </div>
             </div>
             <a class="dropdown-item" href="#">My Profile</a>
             
             <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
       </li>
    </ul>
 </div>

ams_staff/templates/includes/staff_mark_attendance.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Mark Attendence</h1>


    <div>
        <div id="attend" class="p-5">
            <h2>List of Classes</h2>
           <table class="table table-striped table-bordered">
               <thead class="thead-light">
                  <th class="col-3">Semester</th>
                  <th class="col-3">Subject</th>
                  <th class="col-6"></th>
               </thead>
               <tbody>
                 
                {% for s in subject %}
                    <form method="POST" >
                        {% csrf_token %}
                        <tr>
                        <td>{{ s.semester }}</td>
                        <td>{{ s.name }}</td>
                        <td>
                            <a href="{% url 'ams_staff:staff_enter_attendance' s.id %}" class="btn btn-success small">Enter Attendance</a>
                            <button type="button" class="btn btn-info small">Extra Class</button>
                            <button type="button" class="btn btn-primary small">View Students</button>
                        </td>
                        </tr>
                    </form>
                {% endfor %}

               </tbody>
           </table>
        </div>

    </div>




</div>
{% endblock %}

ams_staff/templates/includes/staff_report.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Report</h1>

</div>
{% endblock %}

ams_staff/templates/includes/staff_select_subject.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Select subject</h1>

</div>
{% endblock %}

ams_staff/templates/includes/staff_sidebar.html
{% load static %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
       <div id="sidebar-menu" class="sidebar-menu">
         <ul> 
            <li class="menu-title">
            <span></span>
         </li>
            
          
            <li class="submenu">
               <a href="#"><i class="fas fa-user-graduate" aria-hidden="true"></i> <span> Student</span> <span class="menu-arrow"></span></a>
               <ul>
                  <li><a href="{% url 'ams_staff:staff_view_students' %}">View students</a></li>
                  <li><a href="{% url 'ams_staff:add_student' %}">Add student</a></li>
               </ul>
            </li>
            <li class="submenu">
               <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span class="menu-arrow"></span></a>
               <ul>
                  
                  <li><a href="{% url 'ams_staff:staff_select_subject' %}">Select subject</a></li>
                  <li><a href="{% url 'ams_staff:staff_edit_subject' %}">Subject Edit</a></li>
               </ul>
            </li>
            <li>
               <a href="{% url 'ams_staff:staff_mark_attendance' %}"><i class="fa fa-calendar" aria-hidden="true"></i> <span>Mark Attendence</span></a>
            </li>
            <li>
               <a href="{% url 'ams_staff:staff_view_attendance' %}"><i class="fa fa-calendar" aria-hidden="true"></i> <span>View Attendence</span></a>
            </li>
            <li>
               <a href="{% url 'ams_staff:attendance_report' %}"><i class="fa fa-calendar" aria-hidden="true"></i> <span>Report</span></a>
            </li>
            <li>
               <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt "></i> <span>Logout</span></a>
            </li>
         </ul>



        



        
       </div>
    </div>
 </div>

ams_staff/templates/includes/staff_view_attendance.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>View Attendence</h1>

</div>
{% endblock %}

ams_staff/templates/includes/staff_view_student.html
{% extends 'staff_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>View Students</h1>

    <div class="card card-table">
            <div class="card-body">
               <div class="table-responsive">
                  <table id="table_id" class="table table-hover table-center mb-0">
                     <thead>
                        <tr>
                           <th>ID</th>
                           <th>Name</th>
                           <th>Email</th>
                           <th class="text-right">Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     {%  for i in students %}


                        <tr>
                           <td>{{i.id}}</td>
                           <td>
                              <h2 class="table-avatar">
                                 <a href="#">{{i.first_name}}&nbsp;{{i.last_name}}</a>
                              </h2>
                           </td>
                           <td>{{i.email}}</td>
                
                           <td class="text-right">
                              <div class="actions">
                                 <a href="#" class="btn btn-sm bg-success-light mr-2">
                                 <i class="fas fa-pen"></i>
                                 </a>
                                 <a href="#" class="btn btn-sm bg-danger-light">
                                 <i class="fas fa-trash"></i>
                                 </a>
                              </div>
                           </td>
                        </tr>
                     {% endfor %}  
                     </tbody>
                  </table>
               </div>
            </div>
    </div>



    </div>

</div>
{% endblock %}