ams_admin/urls.py
from django.urls import path
from . import views


app_name = 'ams_admin'

urlpatterns = [
    
    path('admin-base/',views.admin_base,name='admin_base'),

    # verify staff
    path('verify-staff/',views.verify_staff,name='verify_staff'),
    path('verify-staff/verify/<int:id>',views.verify_staff_verify,name="verify_staff_verify"),
    path('verify-staff/remove/<int:id>',views.verify_staff_remove,name="verify_staff_remove"),


    # view students
    path('view-students/',views.view_students,name='view_students'),

    # view attendance
    path('view-attendance/',views.view_attendance,name='view_attendance'),


    # semester
    path('view-semesters/',views.view_semesters,name='view_semesters'),
    path('semester-add/',views.semester_add,name='semester_add'),
    
    

    # session year
    path('view-session-years/',views.view_session_years,name='view_session_years'),
    path('add-session-year/',views.add_session_year,name='add_session_year'),
    path('edit-session-year/<str:id>',views.edit_session_year,name='edit_session_year'),
    path('update-session-year/',views.update_session_year,name='update_session_year'),
    path('delete-session-year/<str:id>',views.delete_session_year,name='delete_session_year'),

    
    
    # subject
    path('view-subjects/',views.view_subjects,name='view_subjects'),
    path('add-subject/',views.add_subject,name='add_subject'),
    path('edit-subject/<str:id>',views.edit_subject,name='edit_subject'),
    path('update-subject/',views.update_subject,name='update_subject'),
    path('delete-subject/<str:id>',views.delete_subject,name='delete_subject'),
    

]

attende/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('ams_admin/', include('ams_admin.urls')),
    path('ams_staff/', include('ams_staff.urls')),
    path('ams_student/', include('ams_student.urls')),

   

    
  

] + static (settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

ams_admin/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
#from ams_staff.models import Student

# Create your models here.




class Session_Year(models.Model):
    session_start=models.CharField(max_length=100)
    session_end=models.CharField(max_length=100)

    def __str__(self):
        return self.session_start + ' To ' + self.session_end
    
class Semester(models.Model):
    name=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    year = models.ForeignKey(Session_Year,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name
    
class Staff(models.Model):
    admin = models.OneToOneField(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.admin.username
    
class Subject(models.Model):
    name=models.CharField(max_length=100)
    semester=models.ForeignKey(Semester,on_delete=models.CASCADE,null=True)
    staff=models.ForeignKey(Staff,on_delete=models.CASCADE,null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self) :
        return self.name
    

ams_admin/forms.py
from django import forms
from accounts.models import Profile
class StaffRegisterForm(forms.Form):
    first_name = forms.CharField(label="First name", max_length=100)
    last_name = forms.CharField(label="Last name", max_length=100)
    email = forms.EmailField(label='Email')
    username = forms.CharField(label="Username")
    password = forms.CharField(widget=forms.PasswordInput())
 

ams_admin/views.py
from django.shortcuts import render,redirect
from accounts.models import Profile
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required

from ams_admin.models import Session_Year,Semester,Subject,Staff
from django.contrib import messages

@login_required
def admin_base(request):
    return render(request,'admin_base.html')


# verify staff
@login_required
def verify_staff(request):
    if request.user.profile.role == 0:
        unverified = User.objects.filter(
            profile__is_verified = False
        ).exclude(
            profile__role = 0
        ).exclude(
            profile__role = 2
        ).exclude(
            username = 'superadmin'
        )
        
        context = {
            'unverified' : unverified
        }
        return render(request,'includes/verify_staff.html',context)
    else:
        return render(request,'restricted.html')
    
@login_required
def verify_staff_verify(request,id):
    if request.user.profile.role == 0:
        staff = User.objects.get(pk = id)
        
        staff.profile.is_verified = True
        staff.save()

        return redirect('ams_admin:verify_staff')
    else:
        return render(request,'restricted.html')
    
@login_required
def verify_staff_remove(request,id):
    if request.user.profile.role == 0:
        staff = User.objects.get(pk = id)
        staff.delete()
        return redirect('ams_admin:verify_staff')
    else:
        return render(request,'restricted.html')



# view student
def view_students(request):
    students = User.objects.all().filter(profile__role = 2)
    context = {
        'students': students
    }
    return render(request,'includes/view_student.html',context)



# view attendance
def view_attendance(request):
    return render(request,'includes/view_attendance.html')


# semester
def view_semesters(request):
    return render(request,'includes/view_semesters.html')

def semester_add(request):

    return render(request,'includes/semester_add.html')



# session year
def view_session_years(request):
    session=Session_Year.objects.all()

    context ={
        'session':session
    }
    return render(request,'includes/view_session_years.html',context)

def add_session_year(request):
    if request.method == "POST":
        session_year_start = request.POST.get('session_year_start')
        session_year_end = request.POST.get('session_year_end')

        session = Session_Year (
            session_start = session_year_start ,
            session_end = session_year_end
        )
        session.save()
        messages.success(request,'Session Are Successfully Created')
        return redirect('ams_admin:add_session_year')

    return render(request,'includes/add_session_year.html')

def edit_session_year(request,id):
    session=Session_Year.objects.filter(id=id)

    context ={
        'session':session
    }

    return render (request,'includes/edit_session_year.html',context)

def update_session_year(request):
    if request.method == "POST": 
        session_id =request.POST.get('session_id')
        session_year_start =request.POST.get('session_year_start')
        session_year_end =request.POST.get('session_year_end')

        session = Session_Year(
            id = session_id,
            session_start =session_year_start,
            session_end =session_year_end,
        )
        session.save()
        messages.success(request,'Session Are Successfully Updated !')
        return redirect('ams_admin:view_session_years')
    
def delete_session_year(request,id):
    session = Session_Year.objects.filter(id = id)
    session.delete()
    messages.success(request,'Session Are Successfully Deleted !')
    return redirect('ams_admin:view_session_years')   

    



# subjects
def view_subjects(request):
    subject = Subject.objects.all()
    
    context = {
        'subject':subject,
        
    }
    return render(request,'includes/view_subjects.html',context)

def add_subject(request):
    semester = Semester.objects.all()
    staffs = User.objects.all().filter(profile__role = 1)
    
    if request.method == "POST":
        subject_name = request.POST.get( 'subject_name')
        semester_id= request.POST.get('semester_id')
        staff_id = request.POST.get('staff_id')

        semester=Semester.objects.get(id=semester_id)
        staff = None
        #try:
        user = User.objects.get(pk = staff_id)
        staff = Staff.objects.get(admin = user)
        #except:
        #    print("Staff Does not exist")
        subject = Subject (
            name = subject_name,
            semester = semester,
            staff = staff,
        )       
        subject.save()
        messages.success(request,'Subjects are successfully added !')
        return redirect('ams_admin:add_subject')
    
    context = {
        'semester':semester,
        'staffs' :staffs,
    }

    return render(request,'includes/add_subject.html',context)

def edit_subject(request,id):
    subject=Subject.objects.get(id=id)
    semester=Semester.objects.all()
    staffs = User.objects.all().filter(profile__role = 1)
    

    context = {
        'subject':subject,
        'semester':semester,
        'staffs':staffs,
    }

    return render(request,'includes/edit_subject.html',context)

def update_subject(request):
    

    if request.method == "POST":
        subject_id=request.POST.get('subject_id')
        semester_id=request.POST.get('semester_id')
        subject_name=request.POST.get('subject_name')
        staff_id=request.POST.get('staff_id')

        semester=Semester.objects.get(id = semester_id)
        staff=Staff.objects.get(staff_id = staff_id)
        subject=Subject(
            id=subject_id,
            name=subject_name,
            semester=semester,
            staff=staff,
        )
        subject.save()
        messages.success(request,'Subject are successfully Updated')
        return redirect('ams_admin:view_subjects')
    return render(request,'includes/edit_subject.html')

def delete_subject(request,id):
    subject=Subject.objects.filter(id=id)
    subject.delete()
    messages.success(request,'Subject are successfully Deleted')
    return redirect('ams_admin:view_subjects')


def semester_add(request):
    if request.method == "POST":
        semester_name=request.POST.get('semester_name')

        semester= Semester (
            name=semester_name,
        )
        semester.save()
        messages.success(request,'Semester are successfully Created')
        return redirect('ams_admin:semester_add')
    
    return render(request,'includes/semester_add.html')

def view_semesters(request):
    semester=Semester.objects.all()
    context= {
        'semester':semester,
    }
    
    
    return render(request,'includes/view_semesters.html',context)





    










ams_admin/templates/includes/add_session.html
{% extends 'admin_base.html' %}
{% block content %}


    <div class="content container-fluid">
    
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Add Session</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="subjects.html">Session</a></li>
                        <li class="breadcrumb-item active">Add Session</li>
                    </ul>
                </div>
            </div>
        </div>
        {% include 'includes/messages.html' %}
        <div class="row">
            <div class="col-sm-12">
                 <div class="card">
                    <div class="card-body">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="row">
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Session Information</span></h5>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session Start</label>
                                       <div>
                                          <input type="date" class="form-control" name="session_year_start" required>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session End</label>
                                       <div>
                                          <input type="date" class="form-control" name="session_year_end" required>
                                       </div>
                                    </div>
                                 </div>
                                
                                <div class="col-12 mt-4 ">
                                    <button type="submit" class="btn btn-primary">Add Session</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    

{% endblock %}

ams_admin/templates/includes/add_session_year.html
{% extends 'admin_base.html' %}
{% block content %}


    <div class="content container-fluid">
    
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Add Session</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="subjects.html">Session</a></li>
                        <li class="breadcrumb-item active">Add Session</li>
                    </ul>
                </div>
            </div>
        </div>
        {% include 'includes/messages.html' %}
        <div class="row">
            <div class="col-sm-12">
                 <div class="card">
                    <div class="card-body">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="row">
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Session Information</span></h5>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session Start</label>
                                       <div>
                                          <input type="date" class="form-control" name="session_year_start" required>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session End</label>
                                       <div>
                                          <input type="date" class="form-control" name="session_year_end" required>
                                       </div>
                                    </div>
                                 </div>
                                
                                <div class="col-12 mt-4 ">
                                    <button type="submit" class="btn btn-primary">Add Session</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    


{% endblock %}

ams_admin/templates/includes/edit_session_year.html
{% extends 'admin_base.html' %}
{% block content %}


    <div class="content container-fluid">
    
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Edit Session</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="subjects.html">Session</a></li>
                        <li class="breadcrumb-item active">Edit Session</li>
                    </ul>
                </div>
            </div>
        </div>
        {% include 'includes/messages.html' %}
        <div class="row">
            <div class="col-sm-12">
                 <div class="card">
                    <div class="card-body">
                        <form action="{% url 'ams_admin:update_session_year' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Session Information</span></h5>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session Start</label>
                                       <div>
                                          <input type="text" class="form-control" name="session_id" value="{% for i in session %}{{i.id}}{% endfor %}" required hidden>
                                          <input type="date" class="form-control" name="session_year_start" value="{% for i in session %}{{i.session_start}}{% endfor %}" required>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                       <label>Session End</label>
                                       <div>
                                          <input type="date" class="form-control" name="session_year_end" value="{% for i in session %}{{i.session_end}}{% endfor %}" required>
                                       </div>
                                    </div>
                                 </div>
                                
                                <div class="col-12 mt-4 ">
                                    <button type="submit" class="btn btn-primary">Update Session</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    

{% endblock %}

ams_admin/templates/includes/edit_subject.html
{% extends 'admin_base.html' %}
{% block content %}


    <div class="content container-fluid">
    
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Edit Subject</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="subjects.html">Subject</a></li>
                        <li class="breadcrumb-item active">Edit Subject</li>
                    </ul>
                </div>
            </div>
        </div>
        {% include 'includes/messages.html' %}
        <div class="row">
            <div class="col-sm-12">
                 <div class="card">
                    <div class="card-body">
                        <form action="{% url 'ams_admin:update_subject' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                 <div class="col-12">
                                    <h5 class="form-title"><span>Subject Information</span></h5>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Subject Name</label>
                                        <input type="text" class="form-control" name="subject_name" value="{{subject.name}}" required>
                                        <input type="text" class="form-control" name="subject_id" value="{{subject.id}}"required  hidden>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <label>Semester</label>
                                    <select class="form-control" name="semester_id" required>
                                        <option>Select Semester</option>
                                         {% for i in semester %}
                                        <option value="{{i.id}}">{{i.name}}</option>
                                         {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                        <label>Staff</label>
                                        <select class="form-control" name="staff_id" required>
                                          <option>Select staff</option>
                                            {% for i in staffs %}
                                          <option value="{{i.id}}">{{i.first_name}}&nbsp;{{i.last_name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                
                                <div class="col-12 mt-4 ">
                                    <button type="submit" class="btn btn-primary">Update Subject</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    

{% endblock %}

ams_admin/templates/includes/footer.html
{% load static %}

<footer>
    {% comment %} <p>Attendance Management System</p> {% endcomment %}
            
</footer>

ams_admin/templates/includes/sidebar.html
{% load static %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
       <div id="sidebar-menu" class="sidebar-menu">
          <ul>
             <li class="menu-title">
                <span></span>
             </li>
             <li>
                <a href="{% url 'ams_admin:verify_staff' %}"><i class="fas fa-chalkboard-teacher"></i><span>Verify Staff</span></a>
             </li>
             
             <li>
                <a href="{% url 'ams_admin:view_students' %}"><i class="fas fa-user-graduate"></i> <span>View Student</span></a>
             </li>
             <li>
                <a href="{% url 'ams_admin:view_attendance' %}"><i class="fa fa-calendar" aria-hidden="true"></i> <span>View Attendence</span></a>
             </li>
             <li class="submenu">
                <a href="#"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <span> Semester</span> <span class="menu-arrow"></span></a>
                <ul>
                   <li><a href="{% url 'ams_admin:view_semesters' %}">View Semesters</a></li>
                   <li><a href="{% url 'ams_admin:semester_add' %}">Add Semester</a></li>
                </ul>
             </li>
             <li class="submenu">
               <a href="#"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <span> Session year</span> <span class="menu-arrow"></span></a>
               <ul>
                  <li><a href="{% url 'ams_admin:view_session_years' %}">View session years</a></li>
                  <li><a href="{% url 'ams_admin:add_session_year' %}">Add session year</a></li>
               </ul>
            </li>
             <li class="submenu">
                <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span class="menu-arrow"></span></a>
                <ul>
                   
                   <li><a href="{% url 'ams_admin:view_subjects' %}">View Subjects</a></li>
                   <li><a href="{% url 'ams_admin:add_subject' %}">Add Subject</a></li>
                </ul>
             </li>
             <li>
                <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt "></i> <span>Logout</span></a>
             </li>
          </ul>

         </div>
    </div>
 </div>

ams_admin/templates/includes/verify_staff.html
{% extends 'admin_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>Verify Staff</h1>
    
    <div class="card-container">
        {% for u in unverified %}
        <div class="card">
            <form onsubmit="return confirm('Do you confirm?')"  method="POST" >
                {% csrf_token %}
                <h3>{{ u.first_name }} {{ u.last_name }}</h3>
                <p>@{{ u.username }}</p>
                <p>{{ u.email }}</p>    
                <br>
                
                <button type="submit" formaction = {% url 'ams_admin:verify_staff_verify' u.id %}  class="ams-primary-button" >Verify</button>
                <button type="submit" formaction = {% url 'ams_admin:verify_staff_remove' u.id %} class="red-button" >Remove</button>  
           
            </form>
        </div>
        {% endfor %}


    </div>

</div>
{% endblock %}

ams_admin/templates/includes/view_attendance.html
{% extends 'admin_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>View Attendance</h1>

    <div>
        This is in admin module
    </div>

</div>
{% endblock %}

ams_admin/templates/includes/view_session_years.html
{% extends 'admin_base.html' %}
{% block content %}

<div class="content container-fluid">
    <div class="page-header">
       <div class="row align-items-center">
          <div class="col">
             <h3 class="page-title">Subject</h3>
             <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Subject</li>
             </ul>
          </div>
          
          <div class="col-auto text-right float-right ml-auto">
             <a href="#" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Download</a>
             <a href="add-student.html" class="btn btn-primary"><i class="fas fa-plus"></i></a>
          </div>
       </div>
    </div>
    {% include 'includes/messages.html' %}
    <div class="row">
       <div class="col-sm-12">
          <div class="card card-table">
             <div class="card-body">
                <div class="table-responsive">
                   <table id="table_id" class="table table-hover table-center mb-0">
                      <thead>
                         <tr>
                            <th>ID</th>
                            <th>Session Start</th>
                            <th>Session End</th>
                            <th class="text-right">Action</th>
                         </tr>
                      </thead>
                      <tbody>
                      {%  for i in session%}


                         <tr>
                            <td>{{i.id}}</td>
                            <td>{{i.session_start}}</td>
                            <td>{{i.session_end}}</td>

                            <td class="text-right">
                               <div class="actions">
                                  <a href="{% url 'ams_admin:edit_session_year' i.id %}" class="btn btn-sm bg-success-light mr-2">
                                  <i class="fas fa-pen"></i>
                                  </a>
                                  <a href="{% url 'ams_admin:delete_session_year' i.id %}" class="btn btn-sm bg-danger-light">
                                  <i class="fas fa-trash"></i>
                                  </a>
                               </div>
                            </td>
                         </tr>
                      {% endfor %}  
                      </tbody>
                   </table>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>


{% endblock %}

ams_admin/templates/includes/view_subjects.html
{% extends 'admin_base.html' %}
{% block content %}
<div class="tab-ams">
    <h1>View subjects</h1>


    <div class="content container-fluid">
    <div class="page-header">
       <div class="row align-items-center">
          <div class="col">
             
             <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Subject</li>
             </ul>
          </div>
       </div>
    </div>
    {% include 'includes/messages.html' %}
    <div class="row">
       <div class="col-sm-12">
          <div class="card card-table">
             <div class="card-body">
                <div class="table-responsive">
                   <table id="table_id" class="table table-hover table-center mb-0">
                      <thead>
                         <tr>
                            <th>ID</th>
                            <th>Subject Name</th>
                            <th>Semester</th>
                            <th>Staff</th>
                            
                            <th class="text-right">Action</th>
                         </tr>
                      </thead>
                      <tbody>
                      {%  for i in subject %}


                         <tr>
                            <td>{{i.id}}</td>
                            <td>{{i.name}}</td>
                            <td>{{i.semester}}</td>
                            <td>{{ i.staff.admin.first_name}}&nbsp;{{i.staff.admin.last_name}}</td>
                            
                            

                            <td class="text-right">
                               <div class="actions">
                                  <a href="{% url 'ams_admin:edit_subject' i.id %}" class="btn btn-sm bg-success-light mr-2">
                                  <i class="fas fa-pen"></i>
                                  </a>
                                  <a href="{% url 'ams_admin:delete_subject' i.id %}" class="btn btn-sm bg-danger-light">
                                  <i class="fas fa-trash"></i>
                                  </a>
                               </div>
                            </td>
                         </tr>
                      {% endfor %}  
                      </tbody>
                   </table>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>




</div>
{% endblock %}